[package]
name = "bela-sys"
version = "0.1.0"
authors = ["Andrew C. Smith <andrewchristophersmith@gmail.com>"]
links = "bela"

[build-dependencies]
bindgen = "0.35"

[dev-dependencies]
libc = "0.2"
nix = "0.10"
